import { StyleSheet } from "react-native";

export default StyleSheet.create({
  buttonContainer: {
    flexDirection: "row",
    alignItems: "center",
    padding: 10,
    backgroundColor: "#f0f0f0",
    borderRadius: 8,
    marginBottom: 10,
  },
  iconContainer: {
    marginRight: 10,
  },
  icon: {
    color: "black",
  },
  modalContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0, 0, 0, 0.75)",
  },
  modalContent: {
    backgroundColor: "white",
    display: "flex",
    alignItems: "center",
    gap: 24,
    padding: 24,
    paddingTop: 32,
    borderRadius: 16,
    width: "86%",
  },
  modalContent2: {
    backgroundColor: "white",
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: 24,
    paddingTop: 32,
    borderRadius: 16,
    width: "86%",
  },
  modalTitle: {
    fontSize: 24,
    fontWeight: "bold",
    lineHeight: 32,
  },
  modalMoodSelection: {
    display: "flex",
    flexDirection: "row",
    alignContent: "center",
    flexWrap: "wrap",
    justifyContent: "center",
    width: "83%",
    gap: 5,
  },
  moodOption: {
    paddingHorizontal: 10,
    paddingVertical: 3,
    borderRadius: 16,
  },
  moodText: {
    fontSize: 12,
    paddingHorizontal: 10,
  },
  moodTextMain: {
    display: "flex",
    justifyContent: "center",
    flexDirection: "row",
    textAlign: "center",
    fontSize: 16,
  },
  moodBorder: {
    borderWidth: "1",
    borderColor: "transparent",
  },
  colorOptionBorder: {
    borderWidth: "1",
    borderColor: "#E3E5E5",
  },
  customMoodInput: {
    width: "100%",
    borderWidth: 1,
    borderColor: "#E3E5E5",
    borderRadius: 8,
    padding: 16,
    backgroundColor: "white",
    fontStyle: "normal",
    lineHeight: 16,
    fontFamily: "Inter_400Regular",
    color: "#090A0A",
  },
  modalButtonContainer: {
    width: "100%",
    alignItems: "center",
  },

  modalButtonContainer2: {
    height: 350,
    marginBottom: 20,
  },
  customColorContainer: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    width: "100%",
  },
  customColorButton: {
    height: 29,
    width: 29,
    borderRadius: 8,
    borderWidth: 2,
    borderColor: "#E3E5E5",
  },
  doneButton: {
    width: "100%",
    display: "flex",
    justifyContent: "center",
    flexDirection: "row",
    textAlign: "center",
    borderRadius: 48,
    padding: 16,
    backgroundColor: "#2F80ED",
  },
  doneButtonText: {
    color: "white",
    fontSize: 16,
    textAlign: "center",
  },
  cancelButton: {
    width: "50%",
    display: "flex",
    justifyContent: "center",
    flexDirection: "row",
    textAlign: "center",
    padding: 16,
    marginTop: 12,
    backgroundColor: "white",
  },
  cancelButton2: {
    width: "100%",
    display: "flex",
    justifyContent: "center",
    flexDirection: "row",
    textAlign: "center",
    padding: 16,
    marginTop: 12,
    backgroundColor: "white",
  },
  cancelButtonText: {
    color: "#2F80ED",
    fontSize: 16,
    textAlign: "center",
  },
  songImage: {
    borderRadius: 8,
    width: 52,
    height: 52,
  },
  innerStyle: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 8,
    backgroundColor: "rgba(0,0,0, 0.30)",
  },

  songContainer: {
    display: "flex",
    flexDirection: "row",
    marginVertical: 4,
    alignItems: "center",
    textAlign: "left",
    gap: 10,
  },
  songList: {
    height: 350,
    display: "flex",
    gap: 10,
  },
  searchBar: {
    padding: 10,
    borderBottomWidth: 1,
    borderBottomColor: "#ccc",
  },
  songDetails: {
    display: "flex",
    flexDirection: "column",
    flex: 1,
  },
  songName: {
    fontSize: 14,
    color: "#090A0A",
    lineHeight: 16,
    textAlign: "left",
  },
  artistName: { color: "#828282", textAlign: "left" },

  selectedSongContainer: {
    backgroundColor: "#F0F0F0",
    borderRadius: 8,
    display: "flex",
    flexDirection: "row",
    marginVertical: 4,
    alignItems: "center",
    textAlign: "left",
    gap: 10,
  },
});
