import { StyleSheet } from "react-native";
export default StyleSheet.create({
  container: {
    height: "100%",
    flexGrow: 1,

    backgroundColor: "white",
    // paddingTop: 24,
    paddingBottom: 16,
    paddingLeft: "7%",
    paddingRight: "7%",
    paddingTop: "7%",
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
  },
  container2: {
    height: "100%",
    flexGrow: 1,

    backgroundColor: "white",
    // paddingTop: 24,
    paddingBottom: 16,
    paddingLeft: "7%",
    paddingRight: "7%",
    paddingTop: "0%",
  },
  scrollContainer: {
    display: "flex",
    height: "93%",
    flexDirection: "column",
    gap: 15,
    alignContent: "space-between",
  },
  editProfileView: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    textAlign: "center",
    justifyContent: "center",
    width: "100%",
    gap: 15,
    paddingBottom: 15,
    borderBottomWidth: 1,
    borderBottomColor: "#F2F4F5",
  },
  editProfileView2: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    textAlign: "center",
    width: "100%",
    height: "100%",
    gap: 15,
    paddingBottom: 15,
  },
  imageOptions: { color: "grey", display: "flex", flexDirection: "column" },
  removeButton: {
    justifyContent: "center",
    flexDirection: "row",
    alignItems: "center",
    borderRadius: 8,
    paddingLeft: 16,
    paddingRight: 16,
    paddingTop: 12,
    textAlign: "center",
    justifyContent: "center",
    flexDirection: "row",
  },
  removeButtonText: {
    fontSize: 12,
    color: "gray",
  },
  profileTextInput: {
    width: "86%",
    display: "flex",
    flexDirection: "column",
    gap: 15,
  },
  text: {
    fontSize: 12,
    color: "#4F4F4F",
    fontWeight: "700",
    letterSpacing: 3,
    textTransform: "uppercase",
    paddingBottom: 10,
  },
  nameInput: {
    width: "100%",
    borderWidth: 1,
    borderColor: "#E3E5E5",
    borderRadius: 8,
    padding: 16,
    backgroundColor: "white",
    fontStyle: "normal",
    lineHeight: 16,
    fontFamily: "Inter_400Regular",
    color: "#090A0A",
  },
  bioInput: {
    width: "100%",
    borderWidth: 1,
    borderColor: "#E3E5E5",
    borderRadius: 8,
    padding: 16,
    paddingTop: 16,
    minHeight: 50,
    fontStyle: "normal",
    lineHeight: 16,
    fontFamily: "Inter_400Regular",
    color: "#090A0A",
  },
  saveButton: {
    justifyContent: "space-between",
    flexDirection: "row",
    alignItems: "center",
    width: "86%",
    borderRadius: 8,
    paddingTop: 12,
    paddingBottom: 12,
    paddingLeft: 16,
    paddingRight: 16,
    backgroundColor: "#2F80ED",
  },

  saveButtonText: {
    color: "white",
  },
  icons: {
    display: "flex",
    flexDirection: "row",
    gap: 5,
  },
  icon: {
    display: "flex",
    flexDirection: "row",
  },
  profilePic: {
    width: 100,
    height: 100,
    borderRadius: 50,
  },
  profilePic2: {
    width: 150,
    height: 150,
    borderRadius: 75,
  },
  textInfo: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    textAlign: "center",
    width: "100%",
    gap: 10,
  },
  name: { fontWeight: "700", fontSize: 20, textAlign: "center" },
  bio: { fontWeight: "300", fontSize: 14, textAlign: "center" },
  image: {
    width: "70%",
  },
  calendar: { height: "100%", marginTop: 0 },

  search: {
    width: "100%",
    display: "flex",
    flexDirection: "row",
    backgroundColor: "#F2F4F5",
    padding: 10,
    borderRadius: 8,
    gap: 10,
  },
  containerEdit: {
    height: "100%",
    backgroundColor: "white",
  },
  searchContainer: {
    width: "100%",
    display: "flex",
    flexDirection: "row",
    backgroundColor: "#F2F4F5",

    padding: 10,
    borderRadius: 8,
    gap: 10,
    marginBottom: 16,
    marginTop: 5,
  },

  searchIcon: {
    display: "flex",
    flexDirection: "column",
    alignContent: "center",
    justifyContent: "center",
  },
  xIcon: {
    position: "absolute",
    top: 10,
    right: 10,
  },
  searchText: { color: "#979C9E", fontSize: 16 },
  searchText2: { color: "#131214", fontSize: 16, padding: 0 },
});
