import { StyleSheet } from "react-native";

const viewPadding = 10;

export default StyleSheet.create({
  container: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    gap: 16,
    backgroundColor: "white",
    paddingTop: 24,
    paddingBottom: 16,
    paddingLeft: "7%",
    paddingRight: "7%",
    marginTop: 44,
    borderRadius: 16,
  },
  headerText: {
    fontSize: 24,
    fontWeight: "bold",
  },
  headerStyle: {
    width: "100%",
  },
  buttonContainer: {
    width: "100%",
    borderRadius: 8,
    paddingLeft: 16,
    paddingRight: 16,
    paddingTop: 12,
    paddingBottom: 12,
    backgroundColor: "#F2F2F2",
    textAlign: "center",
    justifyContent: "space-between",
    flexDirection: "row",
  },
  buttonIcon: {
    justifyContent: "center",
  },
  buttonIcon2: {
    justifyContent: "center",
  },
  buttonText: {
    color: "#979C9E",
    fontWeight: "500",
    fontSize: 16,
    display: "flex",
    alignSelf: "center",
    flexDirection: "column",
    justifyContent: "center",
  },
  imageContainer: {
    flexDirection: "row",
  },
  imageWrapper: {
    width: 300,
    height: 250,
    marginBottom: 16,
    marginHorizontal: 2,
    borderRadius: 0,
    overflow: "hidden",
  },
  image: {
    flex: 1,
  },
  titleInput: {
    width: "100%",
    borderWidth: 1,
    borderColor: "#E3E5E5",
    borderRadius: 8,
    padding: 16,
    backgroundColor: "white",
    fontStyle: "normal",
    lineHeight: 16,
    fontFamily: "Inter_400Regular",
    color: "#090A0A",
  },
  contentInput: {
    width: "100%",
    borderWidth: 1,
    borderColor: "#E3E5E5",
    borderRadius: 8,
    padding: 16,
    paddingTop: 16,
    minHeight: 100,
    fontStyle: "normal",
    lineHeight: 16,
    fontFamily: "Inter_400Regular",
    color: "#090A0A",
  },
  moodInput: {
    // width: "100%",
    // borderRadius: 8,
    // padding: 10,
    // backgroundColor: "#F2F2F2",
    // color: "#979C9E",
    // textAlign: "center",
    // alignItems: "flex-start",
  },
  addButton: {
    justifyContent: "center",
    flexDirection: "row",
    alignItems: "center",
    width: "100%",
    borderRadius: 48,
    paddingLeft: 16,
    paddingRight: 16,
    paddingTop: 12,
    paddingBottom: 12,
    backgroundColor: "#2F80ED",
    textAlign: "center",
    justifyContent: "space-between",
    flexDirection: "row",
  },
  addButtonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "normal",
  },
  list: {
    paddingVertical: viewPadding,
  },
  thoughtContainer: {
    backgroundColor: "#F0F0F0",
    padding: viewPadding,
    marginBottom: viewPadding,
  },
  thoughtImage: {
    width: "100%",
    height: 200,
    marginBottom: viewPadding,
  },
  thoughtTitle: {
    fontSize: 18,
    fontWeight: "bold",
    marginBottom: viewPadding / 2,
  },
  thoughtContent: {
    fontSize: 16,
  },
  thoughtMood: {
    fontSize: 14,
    color: "#888888",
    marginBottom: viewPadding / 2,
  },
});
